---

- name: Install Apache, MySQL and PHP
  hosts: ubuntu
  tasks:
    - name: Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: http traffic
      ufw:
        rule: allow
        direction: in
        name: Apache

    - name: MySql
      apt:
        name: mysql-server
        state: latest

    - name: PHP
      apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
